### ISSUE TITLE
itweet-boot项目下没有提供数据库脚本吗？

### ISSUE THREAD

**Issue by salansun** [itweet/itweet-boot#1]
如题，itweet-boot项目下没有提供数据库脚本吗

**Comment by realxujiang** [comment]
不要数据库脚本，全都是自动初始化，具体请参考快速启动和部署文档，https://github.com/itweet/itweet-boot/blob/master/quickstart.md

**Comment by salansun** [comment]
谢谢。之前没用过springboot，看着像是用的是jpa
